package com.skydown.shared.model

import kotlinx.serialization.Serializable

@Serializable
data class Order(
    val id: String? = null,
    val userEmail: String,
    val customerName: String? = null,
    val customerEmail: String? = null,
    val whatsApp: String? = null,
    val shippingAddress: String? = null,
    val shippingAddressData: ShippingAddressData? = null,
    val shippingZone: String? = null,
    val shippingCountryCode: String? = null,
    val paymentMethod: String? = null,
    val paymentStatus: String? = null,
    val subtotalAmount: Double? = null,
    val shippingAmount: Double? = null,
    val shippingPriceCharged: Double? = null,
    val taxRate: Double? = null,
    val taxAmount: Double? = null,
    val totalAmount: Double? = null,
    val fulfillmentProvider: String? = null,
    val fulfillmentStatus: String? = null,
    val shopifyOrderId: String? = null,
    val shopifyOrderName: String? = null,
    val shopifySyncStatus: String? = null,
    val message: String? = null,
    val items: List<OrderItem>,
    val isCompleted: Boolean,
    val timestampEpochMillis: Long,
)

fun sampleOrders(): List<Order> = listOf(
    Order(
        id = "order-1",
        userEmail = "demo@skydown.app",
        customerName = "Yang D. Nash",
        customerEmail = "demo@skydown.app",
        whatsApp = "+49 170 0000000",
        shippingAddress = "Beispielstrasse 8\n10115 Berlin\nDeutschland",
        shippingAddressData = ShippingAddressData(
            address1 = "Beispielstrasse 8",
            city = "Berlin",
            zip = "10115",
            countryCode = "DE",
            countryName = "Deutschland",
        ),
        shippingZone = "DE",
        shippingCountryCode = "DE",
        paymentMethod = "PayPal",
        paymentStatus = "pending",
        subtotalAmount = 58.0,
        shippingAmount = 4.9,
        shippingPriceCharged = 4.9,
        taxRate = 19.0,
        taxAmount = 10.05,
        totalAmount = 62.9,
        fulfillmentProvider = "manual",
        fulfillmentStatus = "pending",
        shopifySyncStatus = "not_required",
        message = "Bitte kurze Rueckmeldung per Mail.",
        items = listOf(
            OrderItem(
                id = "item-1",
                name = "Skydown T-Shirt",
                quantity = 2,
                size = "M",
                color = "Black",
                sku = "SKY-SHIRT-BLACK-M",
                unitPrice = 29.0,
            ),
        ),
        isCompleted = false,
        timestampEpochMillis = 1_725_100_000_000,
    ),
    Order(
        id = "order-2",
        userEmail = "fans@skydown.app",
        customerName = "Skydown Fan",
        customerEmail = "fans@skydown.app",
        whatsApp = "",
        shippingAddress = "Musterweg 3\n50667 Koeln\nDeutschland",
        shippingAddressData = ShippingAddressData(
            address1 = "Musterweg 3",
            city = "Koeln",
            zip = "50667",
            countryCode = "DE",
            countryName = "Deutschland",
        ),
        shippingZone = "DE",
        shippingCountryCode = "DE",
        paymentMethod = "Bankueberweisung",
        paymentStatus = "confirmed",
        subtotalAmount = 79.0,
        shippingAmount = 0.0,
        shippingPriceCharged = 0.0,
        taxRate = 19.0,
        taxAmount = 12.61,
        totalAmount = 79.0,
        fulfillmentProvider = "podpartner",
        fulfillmentStatus = "in_production",
        shopifyOrderId = "gid://shopify/Order/123",
        shopifyOrderName = "#1001",
        shopifySyncStatus = "submitted",
        message = "",
        items = listOf(
            OrderItem(
                id = "item-2",
                name = "Skydown Hoodie",
                quantity = 1,
                size = "L",
                color = "Black",
                productId = "2",
                shopifyVariantId = "gid://shopify/ProductVariant/111",
                sku = "SKY-HOODIE-BLACK-L",
                unitPrice = 79.0,
            ),
        ),
        isCompleted = true,
        timestampEpochMillis = 1_725_200_000_000,
    ),
)
